### ISSUE TITLE
feat: naabu binary install

### ISSUE THREAD

**Issue by sa7mon** [projectdiscovery/pdtm#266]
### Please describe your feature request:

Support binary install for naabu

### Describe the use case of this feature:

The go install takes a long time and leaves a large cache of Go modules behind. The assets are [there](https://github.com/projectdiscovery/naabu/releases/latest) on the release page so I'm not sure why binary install doesn't happen.

**Comment by sa7mon** [comment]
I don’t know much about dynamic C libraries, but I do know that if I pull down the binary release from GitHub and try to run it, I just need to install libpcap-dev which I think would still be the case with a go install.

**Comment by Mzack9999** [comment]
@sa7mon in the past naabu was installed in that way, but we got multiple reported cases where on older distributions the pre-compiled binary couldn't run due to mismatch with the system shared libraries. So we tried to extend the compatibility and coverage by leveraging the existing go environment which performs the compilation and linking on the system the tool it's going to run, ensuring 100% compatibility

**Comment by sa7mon** [comment]
@Mzack9999 Perhaps the installed libraries could be compared to those of the build system used to compile the binaries?

**Comment by Mzack9999** [comment]
It's going to be difficult to maintain such approach considering the plethora of potential edge cases. At current time the go install way seems the one offering the best advantages, including updating the binary itself via `go install -u`.
To cleanup the system after compilation, you can execute the following command:

```console
$ go clean -cache -testcache -modcache
```
